name: 'helllicht/composer-install'
description: 'helllicht internal composer-install-action'

inputs:
    php-version:
        description: 'PHP Version [default: "7.4"]'
        required: true
        default: "7.4"
    composer-version:
        description: 'Composer Version [default: "2"]'
        required: true
        default: "2"

runs:
    using: "composite"
    steps:
        -   run: echo "Start helllicht/composer-install"
            shell: bash
        -   env:
              ACTION_COMPOSER_VERSION: ${{ inputs.version }}
              ACTION_PHP_VERSION: ${{ inputs.php-version }}
            run: ${{ github.action_path }}/install.sh
            shell: bash
