name: 'helllicht/composer-install'
description: 'helllicht internal composer-install-action'

inputs:
    php-version:
        description: 'PHP Version [default: "7.4"] (options: "7.3", "7.4", "8.0")'
        required: true
        default: "7.4"
    composer-version:
        description: 'Composer Version [default: "2"] (options: "1" or "2")'
        required: true
        default: "2"
    with-dev:
        description: 'With dev requirements (options: "true" or "false")'
        required: false
        default: "false"

runs:
    using: "composite"
    steps:
        -   run: echo "Start helllicht/composer-install"
            shell: bash
        -   run: |
                chmod +x ${{ github.action_path }}/install.sh
                bash ${{ github.action_path }}/install.sh \
                    -p=${{ inputs.php-version }} \
                    -c=${{ inputs.composer-version }} \
                    -d=${{ inputs.with-dev }}
            shell: bash
